import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  sectionContainer: {
    flex: 1,
    backgroundColor: '#10203C',
    padding:20
  },
  headerBox:{
    backgroundColor: '#192845',
    width: '100%',
    alignSelf:'center',
    height: 50,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection:'row',
    alignItems:'center',
    marginTop: 50,
  },
  sexContainer:{
    backgroundColor: '#192845',
    width: '100%',
    height: 80,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection:'row',
    justifyContent:'space-around',
    alignItems:'center',
    marginTop: 20,
  },
  imageContainer:{
    backgroundColor: '#192845',
    width: '100%',
    height: 300,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection:'row',
    justifyContent:'space-around',
    alignItems:'center',
    marginTop: 20,
  },
  placeholderImageTitle:{
    color: '#ECD8E9',
    fontFamily: 'Montserrat-Bold',
    fontSize: 12,
},
  headerText:{
      color: '#ECD8E9',
      fontFamily: 'Montserrat-Bold',
      marginLeft: 5,
      fontSize: 12,
  },
  inputTitle:{
    color: '#ECD8E9',
    fontFamily: 'Montserrat-Bold',
    fontSize: 12,
    marginTop:20
},
FeaturedBox:{
  backgroundColor: '#192845',
  width: '100%',
  height: 80,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  justifyContent: 'center',
  alignItems: 'center',
  marginTop: 20,
},
sexeContainerFemale: {
  backgroundColor: '#4B3051',
  width: '40%',
  height: 50,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
sexeContainerFemaleSelected: {
  backgroundColor: '#4B3051',
  borderWidth:1,
  borderColor:'#d9c3c3',
  width: '40%',
  height: 50,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
sexeContainerMale: {
  backgroundColor: '#1B2F56',
  width: '40%',
  height: 50,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
sexeContainerMaleSelected: {
  backgroundColor: '#1B2F56',
  borderWidth:1,
  borderColor:'#405c94',
  width: '40%',
  height: 50,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
attitudeContainerSelected: {
  backgroundColor: '#1B2F56',
  borderWidth:1,
  borderColor:'#405c94',
  width: '40%',
  height: 50,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
attitudeContainer: {
  backgroundColor: '#101a2e',
  // borderWidth:1,
  // borderColor:'#405c94',
  width: '27%',
  height: 30,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
cameraContainer: {
  backgroundColor: '#101a2e',
  // borderWidth:1,
  // borderColor:'#405c94',
  width: '27%',
  height: 50,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
attitudeContainerSelected: {
  backgroundColor: '#101a2e',
  borderWidth:1,
  borderColor:'#405c94',
  width: '30%',
  height: 30,
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  borderTopRightRadius: 10,
  borderTopLeftRadius: 10,
},
sexeText: {
  color: '#2855AD',
  fontFamily: 'Montserrat-SemiBold',
  fontSize: 15,
},
behaviorText: {
  color: '#2855AD',
  fontFamily: 'Montserrat-SemiBold',
  fontSize: 13,
},
sexeTextFemale: {
  color: '#994556',
  fontFamily: 'Montserrat-SemiBold',
  fontSize: 15,
},
modalStyle: {
  borderTopLeftRadius: 20,
  borderTopRightRadius: 20,
  borderBottomLeftRadius:20,
  borderBottomRightRadius:20,
  width:'95%',
  marginBottom:Platform.OS === "ios" ? 20: "1%",
  alignSelf:'center',
},
modalContentStyle: {
  padding: 20,
  flexDirection: 'column',
  alignItems: 'center',
},
modalizeContainer: {
  padding: 16,
  height: "100%",
  alignItems:'center',
},
modalizeContentContainer:{
  padding: 16,
  height: "100%",
  alignItems:'center',
},
locationContainer:{
  backgroundColor: '#0d1c38',
  height: 40,
  width:'80%',
  borderTopRightRadius: 5,
  borderTopLeftRadius: 5,
  borderBottomLeftRadius: 5,
  borderBottomRightRadius: 5,
  justifyContent:'center',
  marginBottom:10,
  alignSelf:'center',
  alignItems:'center'
},
ModalTextBig:{
  color: '#ECD8E9',
  fontFamily: 'Montserrat-ExtraBold',
  fontSize: 18,
},
ModalTextBigLocation:{
  color: '#ECD8E9',
  fontFamily: 'Montserrat-Bold',
  fontSize: 15,
  marginTop:10
},
ModalTextSubBig:{
  color: '#ECD8E9',
  fontFamily: 'Montserrat-SemiBold',
  fontSize: 13,
  marginTop:10
},
ModalTextSubBigLocation:{
  color: '#ECD8E9',
  fontFamily: 'Montserrat-Regular',
  fontSize: 13,
  marginTop:10
},
});
